#!/usr/bin/with-contenv bashio

WIREGUARD_PORT=$(bashio::config "wireguard_port")
DESTINATION_IP=$(bashio::config "destination_ip")
GATEWAY=$(iptables -nvL -t nat | grep MASQUERADE.*${WIREGUARD_PORT} | awk '{print $8}')

bashio::log.info "Gateway address: ${GATEWAY}"
bashio::log.info "Unsetting route and iptables..."
for route in $(ip route | grep ${GATEWAY} | awk '{print $1}')
do
    ip route del ${route} || true
done

for rule in $(iptables -L --line-number | grep 'Wireguard Client Tools' | awk '{print $1}' | sort -r)
do
    iptables -D FORWARD ${rule} || true
done

for rule in $(iptables -t nat -L --line-number | grep 'Wireguard Client Tools' | awk '{print $1}' | sort -r)
do
    iptables -t nat -D POSTROUTING ${rule} || true
done

for IP in ${DESTINATION_IP}
do
    bashio::log.info "Setting route and iptables for ${IP} ..."
    ip route add ${IP} via ${GATEWAY}
    iptables -A FORWARD -d ${IP} -j ACCEPT -m comment \
        --comment "Generated by Wireguard Client Tools: ${IP}"
    iptables -t nat -A POSTROUTING -d ${IP} -j MASQUERADE -m comment \
        --comment "Generated by Wireguard Client Tools: ${IP}"
done

bashio::log.info "Current route table: "
ip route | grep ${GATEWAY} || true
bashio::log.info "Current rules of iptables: "
iptables -nvL --line-number | grep 'Wireguard Client Tools' || true
iptables -nvL -t nat --line-number | grep 'Wireguard Client Tools' || true

exit 0
